# Generated by Django 6.0.1 on 2026-02-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_amount', models.IntegerField()),
                ('target_role', models.CharField(choices=[('PARENT', 'Parent'), ('TUTOR', 'Tutor')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
