# Generated by Django 6.0.1 on 2026-02-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_subscriptionpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpackage',
            name='target_role',
            field=models.CharField(choices=[('PARENT', 'Parent'), ('TUTOR', 'Tutor'), ('INSTITUTION', 'Institution')], max_length=20),
        ),
    ]
