# Generated by Django 4.2.18 on 2026-03-09 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wallet", "0003_alter_subscriptionpackage_target_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionpackage",
            name="target_role",
            field=models.CharField(
                choices=[
                    ("PARENT", "Parent"),
                    ("TEACHER", "Teacher"),
                    ("INSTITUTION", "Institution"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PaymentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("razorpay_order_id", models.CharField(max_length=128, unique=True)),
                ("razorpay_payment_id", models.CharField(max_length=128)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("status", models.CharField(default="payment.captured", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
