# Generated by Django 6.0.1 on 2026-02-01 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobpost_assigned_admin_jobpost_hourly_rate_and_more'),
        ('users', '0003_tutorkyc_aadhaar_verified_tutorkyc_admin_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintask',
            name='related_kyc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_tasks', to='users.tutorkyc'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_kyc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.tutorkyc'),
        ),
        migrations.AlterField(
            model_name='admintask',
            name='task_type',
            field=models.CharField(choices=[('JOB_APPROVAL', 'Job Approval'), ('KYC_VERIFICATION', 'KYC Verification'), ('TUTOR_VERIFICATION', 'Tutor Verification'), ('DISPUTE_RESOLUTION', 'Dispute Resolution')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('JOB_ASSIGNED', 'Job Assigned to Admin'), ('JOB_APPROVED', 'Job Approved'), ('JOB_REJECTED', 'Job Rejected'), ('JOB_MODIFICATIONS_NEEDED', 'Job Modifications Needed'), ('KYC_ASSIGNED', 'KYC Assigned to Admin'), ('KYC_APPROVED', 'KYC Approved'), ('KYC_REJECTED', 'KYC Rejected'), ('KYC_RESUBMIT', 'KYC Re-submission Required'), ('SYSTEM', 'System Notification')], max_length=50),
        ),
    ]
