# Generated by Django 6.0.1 on 2026-02-04 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_admintask_related_kyc_notification_related_kyc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('PARENT_OPS', 'Parent Operations'), ('TUTOR_OPS', 'Tutor Operations'), ('SUPERADMIN', 'Super Admin')], default='SUPERADMIN', max_length=20)),
                ('pending_job_count', models.PositiveIntegerField(default=0)),
                ('pending_kyc_count', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
