# Generated by Django 6.0.1 on 2026-02-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_board_classlevel_subject_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='department',
            field=models.CharField(choices=[('PARENT_OPS', 'Parent Operations'), ('TUTOR_OPS', 'Tutor Operations'), ('INSTITUTION_OPS', 'Institution Operations'), ('SUPERADMIN', 'Super Admin')], default='SUPERADMIN', max_length=20),
        ),
    ]
