# Generated by Django 6.0.1 on 2026-02-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_adminprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='department',
            field=models.CharField(choices=[('COUNSELLOR', 'Counsellor'), ('TUTOR_OPS', 'Tutor Operations'), ('SUPERADMIN', 'Super Admin')], default='SUPERADMIN', max_length=20),
        ),
    ]
