# Generated by Django 6.0.1 on 2026-02-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_institutejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='tuition_mode',
            field=models.CharField(choices=[('HOME', 'Home Tuition'), ('ONLINE', 'Online'), ('BOTH', 'Both')], default='HOME', max_length=20),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='tutor_gender_preference',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Any', 'Any')], default='Any', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='student_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Any', 'Any')], max_length=20),
        ),
    ]
