# Generated by Django 6.0.1 on 2026-02-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_jobpost_tuition_mode_jobpost_tutor_gender_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='parent_whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
