# Generated by Django 6.0.1 on 2026-02-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_jobpost_parent_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='tuition_mode',
            field=models.CharField(choices=[('HOME', 'Home Tuition'), ('ONLINE_ONE_TO_ONE', 'Online One-to-One'), ('ONLINE_GROUP', 'Online Group'), ('INSTITUTION', 'Institution / Center'), ('BOTH', 'Both / Any')], default='HOME', max_length=20),
        ),
    ]
