# Generated by Django 6.0.1 on 2026-03-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='demo_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
