# Generated by Django 4.2.18 on 2026-03-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_application_demo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='demo_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='demo_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('RESCHEDULE_REQUESTED', 'Reschedule Requested'), ('COMPLETED', 'Completed')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='application',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
