# Generated by Django 6.0.1 on 2026-03-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_application_demo_remarks_application_demo_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='demo_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='parent_notified_for_review',
            field=models.BooleanField(default=False),
        ),
    ]
