# Generated by Django 6.0.1 on 2026-03-21 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_application_demo_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='department',
            field=models.CharField(choices=[('COUNSELLOR', 'Counsellor'), ('TUTOR_OPS', 'Tutor Operations'), ('PARENT_OPS', 'Parent Operations'), ('INSTITUTION_OPS', 'Institution Operations'), ('SUPERADMIN', 'Super Admin')], default='SUPERADMIN', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('MODIFICATIONS_NEEDED', 'Modifications Needed'), ('ACTIVE', 'Active'), ('ASSIGNED', 'Assigned'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='PENDING_APPROVAL', max_length=20),
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(max_length=200)),
                ('lead_phone', models.CharField(blank=True, max_length=20)),
                ('lead_email', models.CharField(blank=True, max_length=200)),
                ('lead_type', models.CharField(choices=[('PARENT', 'Parent Lead'), ('TUTOR', 'Tutor Lead'), ('INSTITUTION', 'Institution Lead'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('scheduled_at', models.DateTimeField(help_text='When the follow-up reminder should trigger')),
                ('reminder_sent', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Admin assigned to this follow-up. Defaults to creator.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_followups', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_followups', to=settings.AUTH_USER_MODEL)),
                ('related_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='jobs.jobpost')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
    ]
