# Generated by Django 6.0.1 on 2026-03-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_add_followup_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='counsellor_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='job_completion_status',
            field=models.CharField(blank=True, choices=[('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped'), ('ON_HOLD', 'On Hold')], default='ONGOING', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20),
        ),
    ]
