# Generated by Django 6.0.1 on 2026-01-12 17:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('PARENT', 'Parent'), ('TEACHER', 'Teacher'), ('ADMIN', 'Admin')], default='PARENT', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], max_length=10, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='tutor_profiles/')),
                ('locality', models.CharField(blank=True, max_length=200, null=True)),
                ('teaching_mode', models.CharField(choices=[('HOME', 'Home'), ('ONLINE', 'Online'), ('BOTH', 'Both')], default='BOTH', max_length=10)),
                ('local_address', models.TextField(blank=True, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('highest_qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('teaching_experience_years', models.PositiveIntegerField(default=0)),
                ('teaching_experience_school_years', models.PositiveIntegerField(default=0)),
                ('expected_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subjects', models.JSONField(blank=True, default=list)),
                ('classes', models.JSONField(blank=True, default=list)),
                ('intermediate_stream', models.CharField(blank=True, max_length=100, null=True)),
                ('intermediate_school', models.CharField(blank=True, max_length=200, null=True)),
                ('intermediate_year', models.PositiveIntegerField(blank=True, null=True)),
                ('intermediate_board', models.CharField(blank=True, max_length=100, null=True)),
                ('highest_stream', models.CharField(blank=True, max_length=100, null=True)),
                ('highest_year', models.PositiveIntegerField(blank=True, null=True)),
                ('highest_university', models.CharField(blank=True, max_length=200, null=True)),
                ('highest_college', models.CharField(blank=True, max_length=200, null=True)),
                ('is_bed', models.BooleanField(default=False)),
                ('is_tet', models.BooleanField(default=False)),
                ('is_mphil', models.BooleanField(default=False)),
                ('is_phd', models.BooleanField(default=False)),
                ('other_certifications', models.TextField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='tutor_docs/')),
                ('intro_video', models.FileField(blank=True, null=True, upload_to='tutor_videos/')),
                ('profile_completion_percentage', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TutorKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_document', models.ImageField(blank=True, null=True, upload_to='kyc_docs/')),
                ('education_certificate', models.FileField(blank=True, null=True, upload_to='kyc_docs/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='kyc_docs/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('submission_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_records', to='users.tutorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TutorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SIGNED_UP', 'Signed Up'), ('PROFILE_INCOMPLETE', 'Profile Incomplete'), ('KYC_SUBMITTED', 'KYC Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('FROZEN', 'Frozen (Max Attempts Exceeded)')], default='SIGNED_UP', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_record', to='users.tutorprofile')),
            ],
        ),
    ]
