# Generated by Django 6.0.1 on 2026-02-01 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contactunlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorkyc',
            name='aadhaar_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutorkyc',
            name='admin_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorkyc',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_kyc_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tutorkyc',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorkyc',
            name='documents_to_resubmit',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tutorkyc',
            name='education_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutorkyc',
            name='pan_document',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_docs/'),
        ),
        migrations.AddField(
            model_name='tutorkyc',
            name='pan_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutorkyc',
            name='passport_document',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_docs/'),
        ),
        migrations.AddField(
            model_name='tutorkyc',
            name='photo_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutorkyc',
            name='police_verification',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/'),
        ),
        migrations.AddField(
            model_name='tutorkyc',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorkyc',
            name='teaching_certificate',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PARENT', 'Parent'), ('TEACHER', 'Teacher'), ('ADMIN', 'Admin'), ('SUPERADMIN', 'Super Admin')], default='PARENT', max_length=20),
        ),
    ]
