# Generated by Django 6.0.1 on 2026-02-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_enquiry_location_enquiry_role_alter_enquiry_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionprofile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='institution_logos/'),
        ),
    ]
