# Generated by Django 6.0.1 on 2026-02-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_institutionprofile_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='external_profile_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
