# Generated by Django 6.0.1 on 2026-02-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_tutorprofile_external_profile_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='city',
            field=models.CharField(default='Lucknow', max_length=100),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='state',
            field=models.CharField(default='Uttar Pradesh', max_length=100),
        ),
    ]
