# Generated by Django 6.0.1 on 2026-02-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_tutorprofile_city_tutorprofile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorkyc',
            name='external_aadhaar_back_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tutorkyc',
            name='external_aadhaar_front_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tutorkyc',
            name='external_education_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tutorkyc',
            name='external_photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
