# Generated by Django 6.0.1 on 2026-02-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_tutorkyc_external_aadhaar_back_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PARENT', 'Parent'), ('TEACHER', 'Teacher'), ('COUNSELLOR', 'Counsellor'), ('TUTOR_ADMIN', 'Tutor Admin'), ('SUPERADMIN', 'Super Admin'), ('INSTITUTION', 'Institution')], default='PARENT', max_length=20),
        ),
    ]
