# Generated by Django 6.0.1 on 2026-02-28 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_enquiry_assigned_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_tutors_records', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by_parents', to='users.tutorprofile')),
            ],
            options={
                'verbose_name_plural': 'Favourite Tutors',
                'unique_together': {('parent', 'tutor')},
            },
        ),
    ]
