# Generated by Django 6.0.1 on 2026-03-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_address_user_area_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='house_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='landmark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
