# Generated by Django 6.0.1 on 2026-03-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_tutorprofile_area_tutorprofile_house_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='class_subjects',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
