# Generated by Django 6.0.1 on 2026-03-07 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_tutorprofile_class_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorkyc',
            old_name='aadhaar_document',
            new_name='aadhaar_back',
        ),
        migrations.RenameField(
            model_name='tutorkyc',
            old_name='aadhaar_verified',
            new_name='aadhaar_back_verified',
        ),
        migrations.RenameField(
            model_name='tutorkyc',
            old_name='photo',
            new_name='aadhaar_front',
        ),
        migrations.RenameField(
            model_name='tutorkyc',
            old_name='education_verified',
            new_name='aadhaar_front_verified',
        ),
        migrations.RenameField(
            model_name='tutorkyc',
            old_name='education_certificate',
            new_name='highest_qualification_certificate',
        ),
        migrations.RenameField(
            model_name='tutorkyc',
            old_name='photo_verified',
            new_name='qualification_verified',
        ),
    ]
